move plugins and config to separate configurable location

diff --git a/shcmanager b/shcmanager
--- a/shcmanager
+++ b/shcmanager
@@ -1,7 +1,60 @@
 # --------------------------
-# "plugins"
+# Load configuration
+config_file=".shcmanager.config"
+work_dir=""
+plugin_dir=""
+
+if [ -f "$config_file" ]; then
+  while IFS='=' read -r key value; do
+    if [ "$key" = "WORK_DIR" ]; then
+      work_dir=$(eval echo "$value")
+      break
+    fi
+  done <"$config_file"
+else
+  echo "Config file not found!"
+  read -p "Press Enter to continue..."
+fi
+
+if [ -n "$work_dir" ]; then
+  plugin_dir="$work_dir/plugins"
+else
+  echo "WORK_DIR not found in config file!"
+  read -p "Press Enter to continue..."
+fi
+
+# --------------------------
+# Actual script starts here
+if [ $# -ne 0 ] && [ "$1" != "create" ]; then
+  echo "Usage: $0 [create <plugin_name>]"
+  exit 1
+elif [ "$1" = "create" ] && [ $# -ne 2 ]; then
+  echo "Usage: $0 [create <plugin_name>]"
+  exit 1
+elif [ "$1" = "create" ]; then
+
+  input_string="$2"
+  filename=$(echo "$input_string" | tr ' ' '_')
+  file_path="$plugin_dir/$filename"
+
+  cat <<EOL >"$file_path"
+install_$filename() {
+  echo "Installing $filename..."
+}
+
+uninstall_$filename() {
+  echo "Uninstalling $filename..."
+}
+EOL
+
+  echo "Plugin template created at $file_path"
+  exit 1
+fi
+
+# --------------------------
+# Load "plugins"
 options=()
-for file in "./plugins"/*; do
+for file in "$plugin_dir"/*; do
   if [ -f "$file" ]; then
     # shellcheck source=./plugins
     source "$file"
@@ -9,31 +62,6 @@ for file in "./plugins"/*; do
     options+=("${filename%.*}")
   fi
 done
-
-# --------------------------
-# Actual script starts here
-if [ $# -ne 0 ] || { [ "$1" = "create" ] && [ $# -ne 2 ]; }; then
-  echo "Usage: $0 [create <plugin_name>]"
-  exit 1
-elif [ "$1" = "create" ]; then
-
-  input_string="$2"
-  filename=$(echo "$input_string" | tr ' ' '_')
-  file_path="./plugins/$filename"
-
-  cat <<EOL >"$file_path"
-install_$filename() {
-
-}
-
-uninstall_$filename() {
-
-}
-EOL
-
-  echo "Plugin template created at $file_path"
-  exit 1
-fi
 
 # --------------------------
 # Menu
@@ -64,11 +92,11 @@ display_menu() {
 
     if [ "$index" -eq "$cursorIndex" ]; then
       if $selectedForInstall_contains; then
-        final_string="  \033[1;32m>\033[0m \033[1;32m${options[index]}\033[0m"
+        final_string="  > \033[1;32m${options[index]}\033[0m"
       elif $selectedForUninstall_contains; then
-        final_string="  \033[1;31m>\033[0m \033[1;31m${options[index]}\033[0m"
+        final_string="  > \033[1;31m${options[index]}\033[0m"
       else
-        final_string="  \033[1;32m>\033[0m ${options[index]}"
+        final_string="  > ${options[index]}"
       fi
     else
       if $selectedForInstall_contains; then
